language: java
jdk: openjdk11
services:
  - mysql
before_install:
  - chmod +x gradlew
  - mysql -e 'CREATE DATABASE test;'
  - mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -e "GRANT ALL ON test.* TO 'root'@'localhost';"