language: java
jdk: openjdk11
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
before_install:
  - chmod +x gradlew
before_script:
  - sleep 15
  - mysql -u root -e 'CREATE DATABASE test;'